### ISSUE TITLE
fount a crash in 1.0.6

### ISSUE THREAD

**Issue by Goooler** [kollerlukas/Camera-Roll-Android-App#216]
I wanted to change a logo picture through Camer-Roll, there's a crash happened.
I checked the app source code which crash happended, and rechanged logo through another gallery app but no crash. The crash should be caused by your code, and with log below

**Comment by Goooler** [comment]
09-03 17:05:07.164 12773-12773/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hexin.ifind.android, PID: 12773
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=-1, data=Intent { act=us.koller.RESULT_ACTION dat=content://media/external/file/158853 flg=0x1 }} to activity {com.hexin.ifind.android/com.hexin.ifind.android.Hexin}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.android.camera.action.CROP dat=content://media/external/file/158853 typ=image/* flg=0x1 (has extras) }
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4440)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4484)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1743)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.android.camera.action.CROP dat=content://media/external/file/158853 typ=image/* flg=0x1 (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2128)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1802)
        at android.app.Activity.startActivityForResult(Activity.java:4514)
        at android.support.v4.app.o.startActivityForResult(BaseFragmentActivityJB.java:48)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
        at android.app.Activity.startActivityForResult(Activity.java:4472)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:856)
        at com.hexin.middleware.activity.a.a(NoViewActivityManager.java:140)
        at com.hexin.middleware.activity.a.a(NoViewActivityManager.java:215)
        at com.hexin.ifind.android.Hexin.onActivityResult(Hexin.java:1478)
        at android.app.Activity.dispatchActivityResult(Activity.java:7317)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4436)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4484)?
        at android.app.ActivityThread.-wrap19(Unknown Source:0)?
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1743)?
        at android.os.Handler.dispatchMessage(Handler.java:106)?
        at android.os.Looper.loop(Looper.java:164)?
        at android.app.ActivityThread.main(ActivityThread.java:6753)?
        at java.lang.reflect.Method.invoke(Native Method)?
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)?
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)?
09-03 17:05:32.695 13173-13173/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hexin.ifind.android, PID: 13173
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=-1, data=null} to activity {com.hexin.ifind.android/com.hexin.ifind.android.Hexin}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.android.camera.action.CROP dat=content://com.hexin.ifind.android.base.authority.fileprovider/root_path/storage/emulated/0/Pictures/1535965527608.jpg typ=image/* flg=0x1 (has extras) }
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4440)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4484)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1743)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.android.camera.action.CROP dat=content://com.hexin.ifind.android.base.authority.fileprovider/root_path/storage/emulated/0/Pictures/1535965527608.jpg typ=image/* flg=0x1 (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2128)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1802)
        at android.app.Activity.startActivityForResult(Activity.java:4514)
        at android.support.v4.app.o.startActivityForResult(BaseFragmentActivityJB.java:48)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
        at android.app.Activity.startActivityForResult(Activity.java:4472)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:856)
        at com.hexin.middleware.activity.a.a(NoViewActivityManager.java:140)
        at com.hexin.middleware.activity.a.a(NoViewActivityManager.java:215)
        at com.hexin.ifind.android.Hexin.onActivityResult(Hexin.java:1478)
        at android.app.Activity.dispatchActivityResult(Activity.java:7317)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4436)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4484)?
        at android.app.ActivityThread.-wrap19(Unknown Source:0)?
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1743)?
        at android.os.Handler.dispatchMessage(Handler.java:106)?
        at android.os.Looper.loop(Looper.java:164)?
        at android.app.ActivityThread.main(ActivityThread.java:6753)?
        at java.lang.reflect.Method.invoke(Native Method)?
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)?
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)?
