### ISSUE TITLE
Scrolling between any 3 pictures back and forth causes app to crash

### ISSUE THREAD

**Issue by Chubukov-Aleksey** [kollerlukas/Camera-Roll-Android-App#67]
Beta 1.6, tested on 5.1.1 CyanogenMod 12.1

Logcat:
```
I/ActivityManager(28374): Start proc 23365:us.koller.cameraroll/u0a303 for activity us.koller.cameraroll/.ui.MainActivity
E/AndroidRuntime(23365): FATAL EXCEPTION: main
E/AndroidRuntime(23365): Process: us.koller.cameraroll, PID: 23365
E/AndroidRuntime(23365): java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@2e37842c
E/AndroidRuntime(23365): 	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
E/AndroidRuntime(23365): 	at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:589)
E/AndroidRuntime(23365): 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw(Unknown Source)
E/AndroidRuntime(23365): 	at android.view.View.draw(View.java:15247)
E/AndroidRuntime(23365): 	at android.view.View.updateDisplayListIfDirty(View.java:14183)
E/AndroidRuntime(23365): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(23365): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(23365): 	at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime(23365): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(23365): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(23365): 	at android.view.View.draw(View.java:15250)
E/AndroidRuntime(23365): 	at android.support.v4.view.ViewPager.draw(Unknown Source)
E/AndroidRuntime(23365): 	at android.view.View.updateDisplayListIfDirty(View.java:14183)
E/AndroidRuntime(23365): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(23365): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(23365): 	at android.view.View.draw(View.java:15250)
E/AndroidRuntime(23365): 	at android.widget.FrameLayout.draw(FrameLayout.java:598)
E/AndroidRuntime(23365): 	at android.view.View.updateDisplayListIfDirty(View.java:14183)
E/AndroidRuntime(23365): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(23365): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(23365): 	at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime(23365): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(23365): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(23365): 	at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime(23365): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(23365): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(23365): 	at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime(23365): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(23365): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(23365): 	at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime(23365): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(23365): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(23365): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(23365): 	at android.view.View.draw(View.java:15250)
E/AndroidRuntime(23365): 	at android.widget.FrameLayout.draw(FrameLayout.java:598)
E/AndroidRuntime(23365): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2906)
E/AndroidRuntime(23365): 	at android.view.View.updateDisplayListIfDirty(View.java:14183)
E/AndroidRuntime(23365): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(23365): 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
E/AndroidRuntime(23365): 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
E/AndroidRuntime(23365): 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
E/AndroidRuntime(23365): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2536)
E/AndroidRuntime(23365): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
E/AndroidRuntime(23365): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
E/AndroidRuntime(23365): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime(23365): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
E/AndroidRuntime(23365): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(23365): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(23365): 	at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime(23365): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(23365): 	at andro
I/ActivityManager(28374): Process us.koller.cameraroll (pid 23365) has died
D/ActivityManager(28374): cleanUpApplicationRecord -- 23365
W/InputMethodManagerService(28374): Got RemoteException sending setActive(false) notification to pid 23365 uid 10303
```

**Comment by kollerlukas** [comment]
Found the issue: There is an issue with my GlideImageDecoder and recycled Bitmaps
This issue only appears on images to small for tiling.

**Comment by kollerlukas** [comment]
should be fixed now https://github.com/kollerlukas/Camera-Roll-Android-App/commit/a544d36755a743d18847a2459637e24538519208
